name-template: "Dude Release "
tag-template: "dude-"
categories:
  - title: "a"
  - title: "b"
  - title: "c"
  - title: "d"
template: |
  yoooo $DATE
  $CHANGES
change-template: '- $TITLE (PR $URL)'
