name: Pull request check

on:
  pull_request:
    branches:
      - master

jobs:
  golangci-lint:
    name: golangci lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1.21.2
